name: ci
on:
  pull_request:
    branches: ["**"]
  push:
    branches: ["feat/metrics-sqlite-eval"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package + test extras
        run: |
          python -m pip install -U pip
          python -m pip install -e ".[test]"
      - name: Run tests
        run: |
          pytest

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install lint extras
        run: |
          python -m pip install -U pip
          python -m pip install -e ".[lint]"
      - name: Ruff check
        run: |
          python -m pip install ruff
          ruff check .
      - name: Type check (mypy)
        run: |
          mypy --ignore-missing-imports src

  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t tal-ci .
